import React from "react";
 import {BrowserRouter,Routes,Route} from "react-router-dom";
import './App.css';
import Navbar from "./components/Navbar";

 import Movie from "./components/movies/Movie";
 import Seats from "./components/seats/Seats";
import Login from "./components/Login";
function App() {
  let movie_data=[    {"Title":"Thor","Year":"2011","Rated":"PG-13","Released":"06 May 2011","Runtime":"115 min","Genre":"Action, Adventure, Fantasy","Director":"Kenneth Branagh","Writer":"Ashley Miller (screenplay), Zack Stentz (screenplay), Don Payne (screenplay), J. Michael Straczynski (story), Mark Protosevich (story), Stan Lee (comic book), Larry Lieber (comic book), Jack Kirby (comic book)","Actors":"Chris Hemsworth, Natalie Portman, Tom Hiddleston, Anthony Hopkins","Plot":"The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.","Language":"English","Country":"USA","Awards":"5 wins & 30 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BOGE4NzU1YTAtNzA3Mi00ZTA2LTg2YmYtMDJmMThiMjlkYjg2XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Rotten Tomatoes","Value":"78%"},{"Source":"Metacritic","Value":"57/100"}],"Metascore":"57","imdbRating":"7.0","imdbVotes":"697,534","imdbID":"tt0800369","Type":"movie","DVD":"13 Sep 2011","BoxOffice":"$181,015,141","Production":"Paramount Pictures","Website":"N/A","Response":"True"},
  {"Title":"Wonder Woman","Year":"2017","Rated":"PG-13","Released":"02 Jun 2017","Runtime":"141 min","Genre":"Action, Adventure, Fantasy, Sci-Fi, War","Director":"Patty Jenkins","Writer":"Allan Heinberg (screenplay by), Zack Snyder (story by), Allan Heinberg (story by), Jason Fuchs (story by), William Moulton Marston (Wonder Woman created by)","Actors":"Gal Gadot, Chris Pine, Connie Nielsen, Robin Wright","Plot":"When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.","Language":"English, German, Dutch, French, Spanish, Chinese, Greek, Ancient (to 1453), North American Indian","Country":"USA, China, Hong Kong","Awards":"17 wins & 54 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNDFmZjgyMTEtYTk5MC00NmY0LWJhZjktOWY2MzI5YjkzODNlXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"},{"Source":"Rotten Tomatoes","Value":"93%"},{"Source":"Metacritic","Value":"76/100"}],"Metascore":"76","imdbRating":"7.4","imdbVotes":"501,523","imdbID":"tt0451279","Type":"movie","DVD":"19 Sep 2017","BoxOffice":"$412,400,625","Production":"Warner Bros. Pictures","Website":"http://wonderwomanfilm.com/","Response":"True"},
  {"Title":"Despicable Me 3","Year":"2017","Rated":"PG","Released":"30 Jun 2017","Runtime":"89 min","Genre":"Animation, Adventure, Comedy, Family, Fantasy, Sci-Fi","Director":"Kyle Balda, Pierre Coffin, Eric Guillon(co-director)","Writer":"Cinco Paul, Ken Daurio","Actors":"Steve Carell, Kristen Wiig, Trey Parker, Miranda Cosgrove","Plot":"Gru meets his long-lost charming, cheerful, and more successful twin brother Dru who wants to team up with him for one last criminal heist.","Language":"English","Country":"USA","Awards":"25 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNjUyNzQ2MTg3Ml5BMl5BanBnXkFtZTgwNzE4NDM3MTI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.3/10"},{"Source":"Rotten Tomatoes","Value":"58%"},{"Source":"Metacritic","Value":"49/100"}],"Metascore":"49","imdbRating":"6.3","imdbVotes":"97,240","imdbID":"tt3469046","Type":"movie","DVD":"05 Dec 2017","BoxOffice":"$264,194,540","Production":"Universal Pictures","Website":"http://www.despicable.me/","Response":"True"},
  {"Title":"Kong: Skull Island","Year":"2017","Rated":"PG-13","Released":"10 Mar 2017","Runtime":"118 min","Genre":"Action, Adventure, Fantasy, Sci-Fi","Director":"Jordan Vogt-Roberts","Writer":"Dan Gilroy (screenplay by), Max Borenstein (screenplay by), Derek Connolly (screenplay by), John Gatins (story by)","Actors":"Tom Hiddleston, Samuel L. Jackson, Brie Larson, John C. Reilly","Plot":"After the Vietnam war, a team of scientists explores an uncharted island in the Pacific, venturing into the domain of the mighty Kong, and must fight to escape a primal Eden.","Language":"English, Vietnamese","Country":"USA, China","Awards":"Nominated for 1 Oscar. Another 1 win & 15 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTUwMzI5ODEwNF5BMl5BanBnXkFtZTgwNjAzNjI2MDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.6/10"},{"Source":"Rotten Tomatoes","Value":"75%"},{"Source":"Metacritic","Value":"62/100"}],"Metascore":"62","imdbRating":"6.6","imdbVotes":"245,567","imdbID":"tt3731562","Type":"movie","DVD":"18 Jul 2017","BoxOffice":"$167,986,460","Production":"Warner Bros. Pictures/Legendary Pictures","Website":"http://kongskullislandmovie.com/","Response":"True"},
  {"Title":"Justice League","Year":"2017","Rated":"PG-13","Released":"17 Nov 2017","Runtime":"120 min","Genre":"Action, Adventure, Fantasy, Sci-Fi","Director":"Zack Snyder","Writer":"Jerry Siegel (Superman created by), Joe Shuster (Superman created by), Chris Terrio (story by), Zack Snyder (story by), Chris Terrio (screenplay by), Joss Whedon (screenplay by), Gardner Fox (Justice League of America created by), Bob Kane (Batman created by), Bill Finger (Batman created by), William Moulton Marston (Wonder Woman created by), Jack Kirby (Fourth World created by)","Actors":"Ben Affleck, Henry Cavill, Amy Adams, Gal Gadot","Plot":"Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his new-found ally, Diana Prince, to face an even greater enemy.","Language":"English, Irish, Russian, Icelandic","Country":"USA, Canada, UK","Awards":"1 win & 6 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BYWVhZjZkYTItOGIwYS00NmRkLWJlYjctMWM0ZjFmMDU4ZjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.4/10"},{"Source":"Rotten Tomatoes","Value":"40%"},{"Source":"Metacritic","Value":"45/100"}],"Metascore":"45","imdbRating":"6.4","imdbVotes":"339,190","imdbID":"tt0974015","Type":"movie","DVD":"13 Mar 2018","BoxOffice":"$227,032,490","Production":"Warner Bros. Pictures","Website":"http://www.justiceleaguethemovie.com/","Response":"True"},
  {"Title":"Ghost in the Shell","Year":"2017","Rated":"PG-13","Released":"31 Mar 2017","Runtime":"107 min","Genre":"Action, Drama, Sci-Fi, Thriller","Director":"Rupert Sanders","Writer":"Shirow Masamune (based on the comic \"The Ghost in the Shell\" by), Jamie Moss (screenplay by), William Wheeler (screenplay by), Ehren Kruger (screenplay by)","Actors":"Scarlett Johansson, Pilou Asbæk, Takeshi Kitano, Juliette Binoche","Plot":"In the near future, Major Mira Killian is the first of her kind: A human saved from a terrible crash, who is cyber-enhanced to be a perfect soldier devoted to stopping the world's most dangerous criminals.","Language":"English, Japanese","Country":"USA, India, Hong Kong, China, UK","Awards":"2 wins & 6 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMzJiNTI3MjItMGJiMy00YzA1LTg2MTItZmE1ZmRhOWQ0NGY1XkEyXkFqcGdeQXVyOTk4MTM0NQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.4/10"},{"Source":"Rotten Tomatoes","Value":"43%"},{"Source":"Metacritic","Value":"52/100"}],"Metascore":"52","imdbRating":"6.4","imdbVotes":"180,511","imdbID":"tt1219827","Type":"movie","DVD":"25 Jul 2017","BoxOffice":"$40,533,014","Production":"Paramount Pictures","Website":"https://www.facebook.com/GhostInTheShellMovie/","Response":"True"},
  {"Title":"Beauty and the Beast","Year":"1991","Rated":"G","Released":"22 Nov 1991","Runtime":"84 min","Genre":"Animation, Family, Fantasy, Musical, Romance","Director":"Gary Trousdale, Kirk Wise","Writer":"Linda Woolverton (animation screenplay by), Brenda Chapman (story by), Chris Sanders (story by), Burny Mattinson (story by), Kevin Harkey (story by), Brian Pimental (story by), Bruce Woodside (story by), Joe Ranft (story by), Tom Ellery (story by), Kelly Asbury (story by), Robert Lence (story by)","Actors":"Robby Benson, Jesse Corti, Rex Everhart, Angela Lansbury","Plot":"A prince cursed to spend his days as a hideous monster sets out to regain his humanity by earning a young woman's love.","Language":"English, French","Country":"USA","Awards":"Won 2 Oscars. Another 24 wins & 25 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMzE5MDM1NDktY2I0OC00YWI5LTk2NzUtYjczNDczOWQxYjM0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"94%"},{"Source":"Metacritic","Value":"95/100"}],"Metascore":"95","imdbRating":"8.0","imdbVotes":"395,317","imdbID":"tt0101414","Type":"movie","DVD":"08 Oct 2002","BoxOffice":"$47,611,331","Production":"Buena Vista","Website":"N/A","Response":"True"},
  {"Title":"The Smurfs","Year":"2011","Rated":"PG","Released":"29 Jul 2011","Runtime":"103 min","Genre":"Animation, Adventure, Comedy, Family, Fantasy","Director":"Raja Gosnell","Writer":"J. David Stem (screenplay by), David N. Weiss (screenplay by), Jay Scherick (screenplay by), David Ronn (screenplay by), J. David Stem (story by), David N. Weiss (story by), Peyo (based on characters created by)","Actors":"Hank Azaria, Neil Patrick Harris, Jayma Mays, Sofía Vergara","Plot":"When the evil wizard Gargamel chases the tiny blue Smurfs out of their village, they tumble from their magical world into New York City.","Language":"English","Country":"USA, Belgium, Canada","Awards":"2 wins & 8 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BOTUzNTczYTMtMzdkOC00ODlkLTk1NDMtYWYxMzQyYzI1YmVjXkEyXkFqcGdeQXVyNDQ2MTMzODA@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"5.4/10"},{"Source":"Rotten Tomatoes","Value":"22%"},{"Source":"Metacritic","Value":"30/100"}],"Metascore":"30","imdbRating":"5.4","imdbVotes":"78,668","imdbID":"tt0472181","Type":"movie","DVD":"02 Dec 2011","BoxOffice":"$142,614,158","Production":"Sony Pictures Columbia","Website":"N/A","Response":"True"},
  {"Title":"The Avengers","Year":"2012","Rated":"PG-13","Released":"04 May 2012","Runtime":"143 min","Genre":"Action, Adventure, Sci-Fi","Director":"Joss Whedon","Writer":"Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)","Actors":"Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth","Plot":"Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.","Language":"English, Russian, Hindi","Country":"USA","Awards":"Nominated for 1 Oscar. Another 38 wins & 79 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.0/10"},{"Source":"Rotten Tomatoes","Value":"92%"},{"Source":"Metacritic","Value":"69/100"}],"Metascore":"69","imdbRating":"8.0","imdbVotes":"1,200,683","imdbID":"tt0848228","Type":"movie","DVD":"25 Sep 2012","BoxOffice":"$623,279,547","Production":"Walt Disney Pictures","Website":"N/A","Response":"True"},
  {"Title":"Power Rangers","Year":"2017","Rated":"PG-13","Released":"24 Mar 2017","Runtime":"124 min","Genre":"Action, Adventure, Sci-Fi","Director":"Dean Israelite","Writer":"John Gatins (screenplay by), Matt Sazama (story by), Burk Sharpless (story by), Michele Mulroney (story by), Kieran Mulroney (story by), Haim Saban (based upon \"Power Rangers\" created by), Saburo Yatsude (television series: \"Super Sentai\"), Shôtarô Ishinomori (television series: \"Super Sentai\")","Actors":"Dacre Montgomery, Naomi Scott, RJ Cyler, Ludi Lin","Plot":"A group of high-school students, who are infused with unique superpowers, harness their abilities in order to save the world.","Language":"English, Mandarin","Country":"USA, Hong Kong, Japan, Mexico, Canada, New Zealand","Awards":"6 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTU1MTkxNzc5NF5BMl5BanBnXkFtZTgwOTM2Mzk3MTI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"5.9/10"},{"Source":"Rotten Tomatoes","Value":"50%"},{"Source":"Metacritic","Value":"44/100"}],"Metascore":"44","imdbRating":"5.9","imdbVotes":"95,172","imdbID":"tt3717490","Type":"movie","DVD":"27 Jun 2017","BoxOffice":"$85,275,488","Production":"Lionsgate Films","Website":"http://www.PowerRangers.Movie","Response":"True"},
  {"Title":"Transformers","Year":"2007","Rated":"PG-13","Released":"03 Jul 2007","Runtime":"144 min","Genre":"Action, Adventure, Sci-Fi","Director":"Michael Bay","Writer":"Roberto Orci (screenplay), Alex Kurtzman (screenplay), John Rogers (story), Roberto Orci (story), Alex Kurtzman (story)","Actors":"Shia LaBeouf, Megan Fox, Josh Duhamel, Tyrese Gibson","Plot":"An ancient struggle between two Cybertronian races, the heroic Autobots and the evil Decepticons, comes to Earth, with a clue to the ultimate power held by a teenager.","Language":"English, Spanish","Country":"USA","Awards":"Nominated for 3 Oscars. Another 20 wins & 41 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNDg1NTU2OWEtM2UzYi00ZWRmLWEwMTktZWNjYWQ1NWM1OThjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Rotten Tomatoes","Value":"58%"},{"Source":"Metacritic","Value":"61/100"}],"Metascore":"61","imdbRating":"7.0","imdbVotes":"573,108","imdbID":"tt0418279","Type":"movie","DVD":"16 Oct 2007","BoxOffice":"$319,014,499","Production":"Dreamworks","Website":"N/A","Response":"True"},
  {"Title":"The Mummy","Year":"1999","Rated":"PG-13","Released":"07 May 1999","Runtime":"124 min","Genre":"Action, Adventure, Fantasy","Director":"Stephen Sommers","Writer":"Stephen Sommers (screen story), Lloyd Fonvielle (screen story), Kevin Jarre (screen story), Stephen Sommers (screenplay)","Actors":"Brendan Fraser, Rachel Weisz, John Hannah, Arnold Vosloo","Plot":"At an archaeological dig in the ancient city of Hamunaptra, an American serving in the French Foreign Legion accidentally awakens a mummy who begins to wreck havoc as he searches for the reincarnation of his long-lost love.","Language":"English, Egyptian (Ancient), Arabic, Chinese, Hebrew, Hungarian","Country":"USA","Awards":"Nominated for 1 Oscar. Another 5 wins & 19 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BOTJiYjBhZDgtMjhiOC00MTIzLThlNGMtMmI1NjIwM2M3YTI5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.0/10"},{"Source":"Rotten Tomatoes","Value":"59%"},{"Source":"Metacritic","Value":"48/100"}],"Metascore":"48","imdbRating":"7.0","imdbVotes":"371,033","imdbID":"tt0120616","Type":"movie","DVD":"28 Sep 1999","BoxOffice":"N/A","Production":"Universal Pictures","Website":"N/A","Response":"True"},
  {"Title":"Kingsman: The Golden Circle","Year":"2017","Rated":"R","Released":"22 Sep 2017","Runtime":"141 min","Genre":"Action, Adventure, Comedy","Director":"Matthew Vaughn","Writer":"Jane Goldman, Matthew Vaughn, Mark Millar (based on the comic book \"The Secret Service\" by), Dave Gibbons (based on the comic book \"The Secret Service\" by)","Actors":"Taron Egerton, Edward Holcroft, Gordon Alexander, Mark Strong","Plot":"When their headquarters are destroyed and the world is held hostage, the Kingsman's journey leads them to the discovery of an allied spy organization in the United States. These two elite secret organizations must band together to defeat a common enemy.","Language":"English, Italian, Swedish","Country":"UK, USA","Awards":"1 win & 4 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMjQ3OTgzMzY4NF5BMl5BanBnXkFtZTgwOTc4OTQyMzI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.8/10"},{"Source":"Rotten Tomatoes","Value":"52%"},{"Source":"Metacritic","Value":"44/100"}],"Metascore":"44","imdbRating":"6.8","imdbVotes":"239,552","imdbID":"tt4649466","Type":"movie","DVD":"12 Dec 2017","BoxOffice":"$99,733,121","Production":"20th Century Fox","Website":"N/A","Response":"True"},
  {"Title":"Fast Five","Year":"2011","Rated":"PG-13","Released":"29 Apr 2011","Runtime":"130 min","Genre":"Action, Adventure, Thriller","Director":"Justin Lin","Writer":"Chris Morgan, Gary Scott Thompson (characters)","Actors":"Vin Diesel, Paul Walker, Jordana Brewster, Tyrese Gibson","Plot":"Dominic Toretto and his crew of street racers plan a massive heist to buy their freedom while in the sights of a powerful Brazilian drug lord and a dangerous federal agent.","Language":"English, Portuguese, Spanish, Italian, French","Country":"USA, Brazil, Japan","Awards":"9 wins & 21 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BMTUxNTk5MTE0OF5BMl5BanBnXkFtZTcwMjA2NzY3NA@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.3/10"},{"Source":"Rotten Tomatoes","Value":"77%"},{"Source":"Metacritic","Value":"66/100"}],"Metascore":"66","imdbRating":"7.3","imdbVotes":"333,452","imdbID":"tt1596343","Type":"movie","DVD":"04 Oct 2011","BoxOffice":"$209,805,005","Production":"Universal Pictures","Website":"N/A","Response":"True"},
  {"Title":"Baywatch","Year":"2017","Rated":"R","Released":"25 May 2017","Runtime":"116 min","Genre":"Action, Comedy, Crime","Director":"Seth Gordon","Writer":"Michael Berk (based on the series \"Baywatch\" created by), Douglas Schwartz (based on the series \"Baywatch\" created by), Gregory J. Bonann (based on the series \"Baywatch\" created by), Jay Scherick (story by), David Ronn (story by), Thomas Lennon (story by), Robert Ben Garant (story by), Damian Shannon (screenplay by), Mark Swift (screenplay by)","Actors":"Dwayne Johnson, Zac Efron, Priyanka Chopra, Alexandra Daddario","Plot":"Devoted lifeguard Mitch Buchannon butts heads with a brash new recruit, as they uncover a criminal plot that threatens the future of the bay.","Language":"English, Spanish","Country":"UK, China, USA","Awards":"3 wins & 10 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNTA4MjQ0ODQzNF5BMl5BanBnXkFtZTgwNzA5NjYzMjI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"5.5/10"},{"Source":"Rotten Tomatoes","Value":"18%"},{"Source":"Metacritic","Value":"37/100"}],"Metascore":"37","imdbRating":"5.5","imdbVotes":"143,549","imdbID":"tt1469304","Type":"movie","DVD":"29 Aug 2017","BoxOffice":"$58,009,442","Production":"Paramount Pictures","Website":"https://www.facebook.com/BaywatchMovie","Response":"True"},
  {"Title":"It","Year":"2017","Rated":"R","Released":"08 Sep 2017","Runtime":"135 min","Genre":"Horror","Director":"Andy Muschietti","Writer":"Chase Palmer (screenplay by), Cary Joji Fukunaga (screenplay by), Gary Dauberman (screenplay by), Stephen King (based on the novel by)","Actors":"Jaeden Martell, Jeremy Ray Taylor, Sophia Lillis, Finn Wolfhard","Plot":"In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town.","Language":"English","Country":"USA, Canada","Awards":"4 wins & 30 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BZDVkZmI0YzAtNzdjYi00ZjhhLWE1ODEtMWMzMWMzNDA0NmQ4XkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.4/10"},{"Source":"Rotten Tomatoes","Value":"86%"},{"Source":"Metacritic","Value":"69/100"}],"Metascore":"69","imdbRating":"7.4","imdbVotes":"392,735","imdbID":"tt1396484","Type":"movie","DVD":"09 Jan 2018","BoxOffice":"$326,898,358","Production":"Warner Bros. Pictures","Website":"http://itthemovie.com/","Response":"True"},
  {"Title":"Blade Runner","Year":"1982","Rated":"R","Released":"25 Jun 1982","Runtime":"117 min","Genre":"Action, Sci-Fi, Thriller","Director":"Ridley Scott","Writer":"Hampton Fancher (screenplay), David Webb Peoples (screenplay), Philip K. Dick (novel)","Actors":"Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos","Plot":"A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.","Language":"English, German, Cantonese, Japanese, Hungarian, Arabic","Country":"USA","Awards":"Nominated for 2 Oscars. Another 11 wins & 16 nominations.","Poster":"https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"89%"},{"Source":"Metacritic","Value":"89/100"}],"Metascore":"89","imdbRating":"8.1","imdbVotes":"639,953","imdbID":"tt0083658","Type":"movie","DVD":"27 Aug 1997","BoxOffice":"N/A","Production":"Warner Bros. Pictures","Website":"N/A","Response":"True"},
  ]
  return (
    <div>
    <Navbar/>
    <BrowserRouter>
      <Routes>
        <Route path="/login" element={<Login/>}/>
      </Routes>
    </BrowserRouter>
    <Movie movie_data={movie_data}/>
    <Seats/>
    </div>
  );
}

export default App;
